name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    #     cache: maven
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml
    - name: Execute jar file
      run: sudo kill -9 `sudo lsof -t -i:90` & sudo java -jar /home/ec2-user/actions-runner/ls/spa/spa/target/docker-0.0.1-SNAPSHOT.jar &

# name: Java CI with Maven

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: self-hosted

#     steps:
#     - uses: actions/checkout@v4
#     - name: run
#       run: cd /home/ec2-user/actions-runner/ls/spa/spa/target
#     - name: jar
#       run: sudo java -jar docker-0.0.1-SNAPSHOT.jar
